readCombine <- function(){
  #Import dependency "dplyr" library
  library(dplyr)
  
  #Activity labels and column names are imported from the working directory
  activities.enum<-read.table("activity_labels.txt")
  labels<-read.table("features.txt")
  
  #Container for the dataframes is initialised
  container<-list()
  
  #Following code runs twice to tidy and shape the imported tables before combining and summarising
  for(i in c("test","train")){
  
  #Filenames are generated
  temp.X<-paste("X_",i,".txt",sep="")
  temp.act<-paste("y_",i,".txt",sep="")
  temp.subj<-paste("subject_",i,".txt",sep="")
  
  #Related activities and subjects files are read for the given set
  activities<-read.table(temp.act)
  X<-read.table(temp.X)
  subjects<-read.table(temp.subj)
  
  #Column labels for activities/subjects/data are appended
  names(activities)<-"activities"
  names(subjects)<-"subject"
  names(X)<-labels[,2]
  
  #Column names are tidied for R and better regex compatibility
  valid_column_names <- make.names(names=names(X), unique=TRUE, allow_ = TRUE)
  names(X)<-valid_column_names
  
  #Only mean and std columns are selected with regex search
  X<-select(X,matches("mean\\.|std",ignore.case = FALSE))
  
  #Activity variables are cleaned, made lower case and underscores removed
  activities<-lapply(activities,function(x){x<-activities.enum[x,2];
                      x<-tolower(x);
                      gsub(pattern="_",replacement="",x)})
  
  #Subject and activities are appended to the dataframe
  X<-cbind(subjects,activities,X)
  
  #Dataframe is pushed into container (not very efficient for large dataframes)
  container[[i]]=X
  }
  
  #The test and training data are combined and made into a data table for faster manipulation
  end<-data.table(rbind(container[["test"]],container[["train"]]))
  
  #Tidy data table is generated by grouping by subject and activities and getting the mean of associated variables
  tidy <- end %>%
    group_by(subject, activities) %>% 
    summarise_each(funs(mean))
  
  #tidy table is returned
  return(tidy)
  
  
}
#Run function
tidy<-readCombine()
